import * as React from "react";
import { useEffect } from "react";
import { styled } from "@mui/material/styles";
import Box from "@mui/material/Box";
import Paper from "@mui/material/Paper";
import Grid from "@mui/material/Grid";
import {
  Button,
  ButtonGroup,
  Card,
  CardActions,
  CardContent,
  CardMedia,
  Container,
  Divider,
  IconButton,
  List,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  ListSubheader,
  Stack,
  Typography,
} from "@mui/material";
import SendIcon from "@mui/icons-material/Send";
import ContactPhoneIcon from "@mui/icons-material/ContactPhone";
import EmailIcon from "@mui/icons-material/Email";
import PublicIcon from "@mui/icons-material/Public";
import DeleteIcon from "@mui/icons-material/Delete";
import FavoriteIcon from "@mui/icons-material/Favorite";
import ModeEditIcon from "@mui/icons-material/ModeEdit";

const App = () => {
  const [data, setData] = React.useState([]);

  const userAction = async () => {
    const response = await fetch("https://jsonplaceholder.typicode.com/users");
    const incomingData = await response.json();
    setData(incomingData);
  };

  useEffect(() => {
    userAction();
  }, []);

  return (
    <Container fixed>
      <Typography gutterBottom variant="h4" textAlign="center" color="primary">
        Here are the list of Random Users generated By using JsonPlaceholder API
        and Materail UI for styling
      </Typography>
      <Box
        sx={{
          bgcolor: "#cfe8fc",
          p: 5,
          display: "flex",
          width: "100%",
          flexWrap: "wrap",
          justifyContent: "center",
        }}
      >
        {data.map((item) => {
          const { id, name, email, phone, website } = item;
          return (
            <Card key={id} sx={{ width: "350px", mt: 2, mr: 2 }}>
              <CardMedia
                component="img"
                alt="karunakar"
                height="200"
                image="https://source.unsplash.com/random"
              />
              <CardContent>
                <Typography gutterBottom variant="h5" textAlign="center">
                  {name}
                </Typography>
                <Divider />
                <List
                  component="div"
                  subheader={<ListSubheader>Details</ListSubheader>}
                >
                  <ListItemButton>
                    <ListItemIcon>
                      <ContactPhoneIcon />
                    </ListItemIcon>
                    <ListItemText primary={phone} />
                  </ListItemButton>
                  <ListItemButton>
                    <ListItemIcon>
                      <EmailIcon />
                    </ListItemIcon>
                    <ListItemText primary={email} />
                  </ListItemButton>
                  <ListItemButton>
                    <ListItemIcon>
                      <PublicIcon />
                    </ListItemIcon>
                    <ListItemText primary={website} />
                  </ListItemButton>
                </List>
              </CardContent>
              <CardActions>
                <Stack
                  direction="row"
                  spacing={2}
                  justifyContent="center"
                  sx={{
                    width: "100%",
                    margin: "-10px 0px 5px",
                  }}
                >
                  <Button variant="outlined" size="large">
                    <FavoriteIcon />
                  </Button>
                  <Button variant="outlined" size="large">
                    <ModeEditIcon />
                  </Button>
                  <Button variant="outlined" size="large">
                    <DeleteIcon />
                  </Button>
                </Stack>
              </CardActions>
            </Card>
          );
        })}
      </Box>
    </Container>
  );
};

export default App;
